{
  "vulnerabilities": [
    {
      "CVSSv3": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:L/I:L/A:N/E:U/RL:O/RC:R",
      "alternativeIds": [],
      "creationTime": "2021-02-26T10:53:46.713767Z",
      "credit": [
        "Beast Glatisant"
      ],
      "cvssScore": 4.2,
      "description": "## Overview\n\nAffected versions of this package are vulnerable to Open Redirect. Redirects are possible within the `aiohttp.web.normalize_path_middleware`.\n## Remediation\nUpgrade `aiohttp` to version 3.7.4 or higher.\n## References\n- [Aiohttp Changelog](https://github.com/aio-libs/aiohttp/blob/master/CHANGES.rst#374-2021-02-25)\n- [GitHub Commit 1](https://github.com/aio-libs/aiohttp/commit/2545222a3853e31ace15d87ae0e2effb7da0c96b)\n- [GitHub Commit 2](https://github.com/aio-libs/aiohttp/commit/5d19ea5e28ae9a55ef1f33ea820f813bf26a7e57)\n",
      "disclosureTime": "2021-02-26T02:11:57Z",
      "exploit": "Unproven",
      "fixedIn": [
        "3.7.4"
      ],
      "functions": [],
      "functions_new": [],
      "id": "SNYK-PYTHON-AIOHTTP-1079232",
      "identifiers": {
        "CVE": [
          "CVE-2021-21330"
        ],
        "CWE": [
          "CWE-601"
        ],
        "GHSA": [
          "GHSA-v6wp-4m6f-gcjg"
        ]
      },
      "language": "python",
      "modificationTime": "2021-02-26T15:46:38.124408Z",
      "moduleName": "aiohttp",
      "packageManager": "pip",
      "packageName": "aiohttp",
      "patches": [],
      "proprietary": false,
      "publicationTime": "2021-02-26T15:46:38.337042Z",
      "references": [
        {
          "title": "Aiohttp Changelog",
          "url": "https://github.com/aio-libs/aiohttp/blob/master/CHANGES.rst%23374-2021-02-25"
        },
        {
          "title": "GitHub Commit 1",
          "url": "https://github.com/aio-libs/aiohttp/commit/2545222a3853e31ace15d87ae0e2effb7da0c96b"
        },
        {
          "title": "GitHub Commit 2",
          "url": "https://github.com/aio-libs/aiohttp/commit/5d19ea5e28ae9a55ef1f33ea820f813bf26a7e57"
        }
      ],
      "semver": {
        "vulnerable": [
          "[,3.7.4)"
        ]
      },
      "severity": "medium",
      "severityWithCritical": "medium",
      "socialTrendAlert": false,
      "title": "Open Redirect",
      "from": [
        "test-manifests@0.0.0",
        "aiohttp-jinja2@1.1.0",
        "aiohttp@3.5.3"
      ],
      "upgradePath": [],
      "isUpgradable": false,
      "isPatchable": false,
      "name": "aiohttp",
      "version": "3.5.3"
    },
    {
      "CVSSv3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L/E:P",
      "alternativeIds": [],
      "creationTime": "2020-09-25T17:30:26.286074Z",
      "credit": [
        "Yeting Li"
      ],
      "cvssScore": 5.3,
      "description": "## Overview\n[jinja2](https://pypi.org/project/Jinja2/) is a template engine written in pure Python. It provides a Django inspired non-XML syntax but supports inline expressions and an optional sandboxed environment.\n\nAffected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS). The ReDoS vulnerability is mainly due to the `_punctuation_re regex` operator and its use of multiple wildcards. The last wildcard is the most exploitable as it searches for trailing punctuation.\r\n\r\nThis issue can be mitigated by using Markdown to format user content instead of the urlize filter, or by implementing request timeouts or limiting process memory.\r\n\r\n### PoC by Yeting Li\r\n```\r\nfrom jinja2.utils import urlize\r\nfrom time import perf_counter\r\n\r\nfor i in range(3):\r\n    text = \"abc@\" + \".\" * (i+1)*5000 + \"!\"\r\n    LEN = len(text)\r\n    BEGIN = perf_counter()\r\n    urlize(text)\r\n    DURATION = perf_counter() - BEGIN\r\n    print(f\"{LEN}: took {DURATION} seconds!\")\r\n```\n\n## Details\n\nDenial of Service (DoS) describes a family of attacks, all aimed at making a system inaccessible to its original and legitimate users. There are many types of DoS attacks, ranging from trying to clog the network pipes to the system by generating a large volume of traffic from many machines (a Distributed Denial of Service - DDoS - attack) to sending crafted requests that cause a system to crash or take a disproportional amount of time to process.\n\nThe Regular expression Denial of Service (ReDoS) is a type of Denial of Service attack. Regular expressions are incredibly powerful, but they aren't very intuitive and can ultimately end up making it easy for attackers to take your site down.\n\nLet’s take the following regular expression as an example:\n```js\nregex = /A(B|C+)+D/\n```\n\nThis regular expression accomplishes the following:\n- `A` The string must start with the letter 'A'\n- `(B|C+)+` The string must then follow the letter A with either the letter 'B' or some number of occurrences of the letter 'C' (the `+` matches one or more times). The `+` at the end of this section states that we can look for one or more matches of this section.\n- `D` Finally, we ensure this section of the string ends with a 'D'\n\nThe expression would match inputs such as `ABBD`, `ABCCCCD`, `ABCBCCCD` and `ACCCCCD`\n\nIt most cases, it doesn't take very long for a regex engine to find a match:\n\n```bash\n$ time node -e '/A(B|C+)+D/.test(\"ACCCCCCCCCCCCCCCCCCCCCCCCCCCCD\")'\n0.04s user 0.01s system 95% cpu 0.052 total\n\n$ time node -e '/A(B|C+)+D/.test(\"ACCCCCCCCCCCCCCCCCCCCCCCCCCCCX\")'\n1.79s user 0.02s system 99% cpu 1.812 total\n```\n\nThe entire process of testing it against a 30 characters long string takes around ~52ms. But when given an invalid string, it takes nearly two seconds to complete the test, over ten times as long as it took to test a valid string. The dramatic difference is due to the way regular expressions get evaluated.\n\nMost Regex engines will work very similarly (with minor differences). The engine will match the first possible way to accept the current character and proceed to the next one. If it then fails to match the next one, it will backtrack and see if there was another way to digest the previous character. If it goes too far down the rabbit hole only to find out the string doesn’t match in the end, and if many characters have multiple valid regex paths, the number of backtracking steps can become very large, resulting in what is known as _catastrophic backtracking_.\n\nLet's look at how our expression runs into this problem, using a shorter string: \"ACCCX\". While it seems fairly straightforward, there are still four different ways that the engine could match those three C's:\n1. CCC\n2. CC+C\n3. C+CC\n4. C+C+C.\n\nThe engine has to try each of those combinations to see if any of them potentially match against the expression. When you combine that with the other steps the engine must take, we can use [RegEx 101 debugger](https://regex101.com/debugger) to see the engine has to take a total of 38 steps before it can determine the string doesn't match.\n\nFrom there, the number of steps the engine must use to validate a string just continues to grow.\n\n| String | Number of C's | Number of steps |\n| -------|-------------:| -----:|\n| ACCCX | 3 | 38\n| ACCCCX | 4 | 71\n| ACCCCCX | 5 | 136\n| ACCCCCCCCCCCCCCX | 14 | 65,553\n\n\nBy the time the string includes 14 C's, the engine has to take over 65,000 steps just to see if the string is valid. These extreme situations can cause them to work very slowly (exponentially related to input size, as shown above), allowing an attacker to exploit this and can cause the service to excessively consume CPU, resulting in a Denial of Service.\n\n## Remediation\nUpgrade `jinja2` to version 2.11.3 or higher.\n## References\n- [GitHub Additional Information](https://github.com/pallets/jinja/blob/ab81fd9c277900c85da0c322a2ff9d68a235b2e6/src/jinja2/utils.py#L20)\n- [GitHub PR](https://github.com/pallets/jinja/pull/1343)\n",
      "disclosureTime": "2020-09-25T17:29:19Z",
      "exploit": "Proof of Concept",
      "fixedIn": [
        "2.11.3"
      ],
      "functions": [],
      "functions_new": [],
      "id": "SNYK-PYTHON-JINJA2-1012994",
      "identifiers": {
        "CVE": [
          "CVE-2020-28493"
        ],
        "CWE": [
          "CWE-400"
        ],
        "GHSA": [
          "GHSA-g3rq-g295-4j3m"
        ]
      },
      "language": "python",
      "modificationTime": "2021-02-01T19:52:16.877030Z",
      "moduleName": "jinja2",
      "packageManager": "pip",
      "packageName": "jinja2",
      "patches": [],
      "proprietary": true,
      "publicationTime": "2021-02-01T19:52:17Z",
      "references": [
        {
          "title": "GitHub Additional Information",
          "url": "https://github.com/pallets/jinja/blob/ab81fd9c277900c85da0c322a2ff9d68a235b2e6/src/jinja2/utils.py%23L20"
        },
        {
          "title": "GitHub PR",
          "url": "https://github.com/pallets/jinja/pull/1343"
        }
      ],
      "semver": {
        "vulnerable": [
          "[,2.11.3)"
        ]
      },
      "severity": "medium",
      "severityWithCritical": "medium",
      "socialTrendAlert": false,
      "title": "Regular Expression Denial of Service (ReDoS)",
      "from": [
        "test-manifests@0.0.0",
        "aiohttp-jinja2@1.1.0",
        "jinja2@2.10"
      ],
      "upgradePath": [],
      "isUpgradable": false,
      "isPatchable": false,
      "name": "jinja2",
      "version": "2.10"
    },
    {
      "CVSSv3": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:C/C:L/I:L/A:L/RL:O",
      "alternativeIds": [],
      "creationTime": "2019-04-07T10:24:16.310959Z",
      "credit": [
        "Unknown"
      ],
      "cvssScore": 6,
      "description": "## Overview\n[jinja2](https://pypi.org/project/Jinja2/) is a template engine written in pure Python. It provides a Django inspired non-XML syntax but supports inline expressions and an optional sandboxed environment.\n\nAffected versions of this package are vulnerable to Sandbox Escape via the `str.format_map`.\n## Remediation\nUpgrade `jinja2` to version 2.10.1 or higher.\n## References\n- [Release Notes](https://palletsprojects.com/blog/jinja-2-10-1-released)\n",
      "disclosureTime": "2019-04-07T00:42:43Z",
      "exploit": "Not Defined",
      "fixedIn": [
        "2.10.1"
      ],
      "functions": [],
      "functions_new": [],
      "id": "SNYK-PYTHON-JINJA2-174126",
      "identifiers": {
        "CVE": [
          "CVE-2019-10906"
        ],
        "CWE": [
          "CWE-265"
        ]
      },
      "language": "python",
      "modificationTime": "2020-06-12T14:36:55.661596Z",
      "moduleName": "jinja2",
      "packageManager": "pip",
      "packageName": "jinja2",
      "patches": [],
      "proprietary": false,
      "publicationTime": "2019-04-07T00:42:43Z",
      "references": [
        {
          "title": "Release Notes",
          "url": "https://palletsprojects.com/blog/jinja-2-10-1-released"
        }
      ],
      "semver": {
        "vulnerable": [
          "[,2.10.1)"
        ]
      },
      "severity": "medium",
      "severityWithCritical": "medium",
      "socialTrendAlert": false,
      "title": "Sandbox Escape",
      "from": [
        "test-manifests@0.0.0",
        "aiohttp-jinja2@1.1.0",
        "jinja2@2.10"
      ],
      "upgradePath": [],
      "isUpgradable": false,
      "isPatchable": false,
      "name": "jinja2",
      "version": "2.10"
    },
    {
      "CVSSv3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "alternativeIds": [],
      "creationTime": "2018-06-27T12:31:22.907000Z",
      "credit": [
        "Unknown"
      ],
      "cvssScore": 9.8,
      "description": "## Overview\n[pyyaml](https://pypi.org/project/PyYAML/) is a YAML parser and emitter for Python.\n\nAffected versions of this package are vulnerable to Arbitrary Code Execution due to using the insecure `yaml.load()` function.\n## Remediation\nUpgrade `pyyaml` to version 4.2b1 or higher.\n## References\n- [GitHub Commit](https://github.com/yaml/pyyaml/commit/bbcf95fa051fdba9bbf879332e2f7999b195cf95)\n- [GitHub PR](https://github.com/yaml/pyyaml/pull/74)\n",
      "disclosureTime": "2017-08-26T12:31:22Z",
      "exploit": "Not Defined",
      "fixedIn": [
        "4.2b1"
      ],
      "functions": [],
      "functions_new": [],
      "id": "SNYK-PYTHON-PYYAML-42159",
      "identifiers": {
        "CVE": [
          "CVE-2017-18342"
        ],
        "CWE": [
          "CWE-94"
        ],
        "GHSA": [
          "GHSA-rprw-h62v-c2w7"
        ]
      },
      "language": "python",
      "modificationTime": "2020-06-12T14:37:04.903304Z",
      "moduleName": "pyyaml",
      "packageManager": "pip",
      "packageName": "pyyaml",
      "patches": [],
      "proprietary": false,
      "publicationTime": "2018-06-28T14:59:11Z",
      "references": [
        {
          "title": "GitHub Commit",
          "url": "https://github.com/yaml/pyyaml/commit/bbcf95fa051fdba9bbf879332e2f7999b195cf95"
        },
        {
          "title": "GitHub PR",
          "url": "https://github.com/yaml/pyyaml/pull/74"
        }
      ],
      "semver": {
        "vulnerable": [
          "[,4.2b1)"
        ]
      },
      "severity": "critical",
      "severityWithCritical": "critical",
      "socialTrendAlert": false,
      "title": "Arbitrary Code Execution",
      "from": [
        "test-manifests@0.0.0",
        "pyyaml@3.13"
      ],
      "upgradePath": [],
      "isUpgradable": false,
      "isPatchable": false,
      "name": "pyyaml",
      "version": "3.13"
    },
    {
      "CVSSv3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "alternativeIds": [],
      "creationTime": "2020-03-02T13:40:20.621517Z",
      "credit": [
        "Riccardo Schirone (Red Hat)"
      ],
      "cvssScore": 9.8,
      "description": "## Overview\n[pyyaml](https://pypi.org/project/PyYAML/) is a YAML parser and emitter for Python.\n\nAffected versions of this package are vulnerable to Arbitrary Code Execution. It is susceptible to arbitrary code execution when it processes untrusted YAML files through the `full_load` method or with the `FullLoader` loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.\n## Remediation\nUpgrade `pyyaml` to version 5.3.1 or higher.\n## References\n- [GitHub Commit](https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0)\n- [GitHub PR](https://github.com/yaml/pyyaml/pull/386)\n- [Redhat Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1807367)\n",
      "disclosureTime": "2020-03-02T00:00:00Z",
      "exploit": "Not Defined",
      "fixedIn": [
        "5.3.1"
      ],
      "functions": [],
      "functions_new": [],
      "id": "SNYK-PYTHON-PYYAML-559098",
      "identifiers": {
        "CVE": [
          "CVE-2020-1747"
        ],
        "CWE": [
          "CWE-20"
        ],
        "GHSA": [
          "GHSA-6757-jp84-gxfx"
        ]
      },
      "language": "python",
      "modificationTime": "2020-06-12T14:36:55.955917Z",
      "moduleName": "pyyaml",
      "packageManager": "pip",
      "packageName": "pyyaml",
      "patches": [],
      "proprietary": false,
      "publicationTime": "2020-03-02T14:05:05Z",
      "references": [
        {
          "title": "GitHub Commit",
          "url": "https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0"
        },
        {
          "title": "GitHub PR",
          "url": "https://github.com/yaml/pyyaml/pull/386"
        },
        {
          "title": "Redhat Bugzilla",
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1807367"
        }
      ],
      "semver": {
        "vulnerable": [
          "[0,5.3.1)"
        ]
      },
      "severity": "critical",
      "severityWithCritical": "critical",
      "socialTrendAlert": false,
      "title": "Arbitrary Code Execution",
      "from": [
        "test-manifests@0.0.0",
        "pyyaml@3.13"
      ],
      "upgradePath": [],
      "isUpgradable": false,
      "isPatchable": false,
      "name": "pyyaml",
      "version": "3.13"
    },
    {
      "CVSSv3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H/E:F/RL:O/RC:C",
      "alternativeIds": [],
      "creationTime": "2020-07-26T08:29:31.478203Z",
      "credit": [
        "Unknown"
      ],
      "cvssScore": 9.8,
      "description": "## Overview\n[pyyaml](https://pypi.org/project/PyYAML/) is a YAML parser and emitter for Python.\n\nAffected versions of this package are vulnerable to Arbitrary Code Execution. It processes untrusted YAML files through the `full_load` method or with the `FullLoader` loader. This is due to an incomplete fix for CVE-2020-1747\n## Remediation\nUpgrade `pyyaml` to version 5.4 or higher.\n## References\n- [Exploit Writeup](https://hackmd.io/@harrier/uiuctf20)\n- [GitHub Commit](https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc)\n- [GitHub Issue](https://github.com/yaml/pyyaml/issues/420)\n- [RedHat Bugzilla Bug](https://bugzilla.redhat.com/show_bug.cgi?id=1860466)\n- [Research Blog Post](https://blog.arxenix.dev/pyyaml-cve/)\n",
      "disclosureTime": "2020-07-22T00:00:00Z",
      "exploit": "Functional",
      "fixedIn": [
        "5.4"
      ],
      "functions": [],
      "functions_new": [],
      "id": "SNYK-PYTHON-PYYAML-590151",
      "identifiers": {
        "CVE": [
          "CVE-2020-14343"
        ],
        "CWE": [
          "CWE-94"
        ]
      },
      "language": "python",
      "modificationTime": "2021-01-20T14:15:00.359860Z",
      "moduleName": "pyyaml",
      "packageManager": "pip",
      "packageName": "pyyaml",
      "patches": [],
      "proprietary": false,
      "publicationTime": "2020-07-26T13:45:01Z",
      "references": [
        {
          "title": "Exploit Writeup",
          "url": "https://hackmd.io/@harrier/uiuctf20"
        },
        {
          "title": "GitHub Commit",
          "url": "https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc"
        },
        {
          "title": "GitHub Issue",
          "url": "https://github.com/yaml/pyyaml/issues/420"
        },
        {
          "title": "RedHat Bugzilla Bug",
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1860466"
        },
        {
          "title": "Research Blog Post",
          "url": "https://blog.arxenix.dev/pyyaml-cve/"
        }
      ],
      "semver": {
        "vulnerable": [
          "[0,5.4)"
        ]
      },
      "severity": "critical",
      "severityWithCritical": "critical",
      "socialTrendAlert": false,
      "title": "Arbitrary Code Execution",
      "from": [
        "test-manifests@0.0.0",
        "pyyaml@3.13"
      ],
      "upgradePath": [],
      "isUpgradable": false,
      "isPatchable": false,
      "name": "pyyaml",
      "version": "3.13"
    }
  ],
  "ok": false,
  "dependencyCount": 14,
  "org": "divyansh42",
  "policy": "# Snyk (https://snyk.io) policy file, patches or ignores known vulnerabilities.\nversion: v1.21.5\nignore: {}\npatch: {}\n",
  "isPrivate": true,
  "licensesPolicy": {
    "severities": {},
    "orgLicenseRules": {
      "AGPL-1.0": {
        "licenseType": "AGPL-1.0",
        "severity": "high",
        "instructions": ""
      },
      "AGPL-3.0": {
        "licenseType": "AGPL-3.0",
        "severity": "high",
        "instructions": ""
      },
      "Artistic-1.0": {
        "licenseType": "Artistic-1.0",
        "severity": "medium",
        "instructions": ""
      },
      "Artistic-2.0": {
        "licenseType": "Artistic-2.0",
        "severity": "medium",
        "instructions": ""
      },
      "CDDL-1.0": {
        "licenseType": "CDDL-1.0",
        "severity": "medium",
        "instructions": ""
      },
      "CPOL-1.02": {
        "licenseType": "CPOL-1.02",
        "severity": "high",
        "instructions": ""
      },
      "EPL-1.0": {
        "licenseType": "EPL-1.0",
        "severity": "medium",
        "instructions": ""
      },
      "GPL-2.0": {
        "licenseType": "GPL-2.0",
        "severity": "high",
        "instructions": ""
      },
      "GPL-3.0": {
        "licenseType": "GPL-3.0",
        "severity": "high",
        "instructions": ""
      },
      "LGPL-2.0": {
        "licenseType": "LGPL-2.0",
        "severity": "medium",
        "instructions": ""
      },
      "LGPL-2.1": {
        "licenseType": "LGPL-2.1",
        "severity": "medium",
        "instructions": ""
      },
      "LGPL-3.0": {
        "licenseType": "LGPL-3.0",
        "severity": "medium",
        "instructions": ""
      },
      "MPL-1.1": {
        "licenseType": "MPL-1.1",
        "severity": "medium",
        "instructions": ""
      },
      "MPL-2.0": {
        "licenseType": "MPL-2.0",
        "severity": "medium",
        "instructions": ""
      },
      "MS-RL": {
        "licenseType": "MS-RL",
        "severity": "medium",
        "instructions": ""
      },
      "SimPL-2.0": {
        "licenseType": "SimPL-2.0",
        "severity": "high",
        "instructions": ""
      }
    }
  },
  "packageManager": "pip",
  "ignoreSettings": null,
  "summary": "6 vulnerable dependency paths",
  "remediation": {
    "unresolved": [
      {
        "CVSSv3": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:L/I:L/A:N/E:U/RL:O/RC:R",
        "alternativeIds": [],
        "creationTime": "2021-02-26T10:53:46.713767Z",
        "credit": [
          "Beast Glatisant"
        ],
        "cvssScore": 4.2,
        "description": "## Overview\n\nAffected versions of this package are vulnerable to Open Redirect. Redirects are possible within the `aiohttp.web.normalize_path_middleware`.\n## Remediation\nUpgrade `aiohttp` to version 3.7.4 or higher.\n## References\n- [Aiohttp Changelog](https://github.com/aio-libs/aiohttp/blob/master/CHANGES.rst#374-2021-02-25)\n- [GitHub Commit 1](https://github.com/aio-libs/aiohttp/commit/2545222a3853e31ace15d87ae0e2effb7da0c96b)\n- [GitHub Commit 2](https://github.com/aio-libs/aiohttp/commit/5d19ea5e28ae9a55ef1f33ea820f813bf26a7e57)\n",
        "disclosureTime": "2021-02-26T02:11:57Z",
        "exploit": "Unproven",
        "fixedIn": [
          "3.7.4"
        ],
        "functions": [],
        "functions_new": [],
        "id": "SNYK-PYTHON-AIOHTTP-1079232",
        "identifiers": {
          "CVE": [
            "CVE-2021-21330"
          ],
          "CWE": [
            "CWE-601"
          ],
          "GHSA": [
            "GHSA-v6wp-4m6f-gcjg"
          ]
        },
        "language": "python",
        "modificationTime": "2021-02-26T15:46:38.124408Z",
        "moduleName": "aiohttp",
        "packageManager": "pip",
        "packageName": "aiohttp",
        "patches": [],
        "proprietary": false,
        "publicationTime": "2021-02-26T15:46:38.337042Z",
        "references": [
          {
            "title": "Aiohttp Changelog",
            "url": "https://github.com/aio-libs/aiohttp/blob/master/CHANGES.rst%23374-2021-02-25"
          },
          {
            "title": "GitHub Commit 1",
            "url": "https://github.com/aio-libs/aiohttp/commit/2545222a3853e31ace15d87ae0e2effb7da0c96b"
          },
          {
            "title": "GitHub Commit 2",
            "url": "https://github.com/aio-libs/aiohttp/commit/5d19ea5e28ae9a55ef1f33ea820f813bf26a7e57"
          }
        ],
        "semver": {
          "vulnerable": [
            "[,3.7.4)"
          ]
        },
        "severity": "medium",
        "severityWithCritical": "medium",
        "socialTrendAlert": false,
        "title": "Open Redirect",
        "from": [
          "test-manifests@0.0.0",
          "aiohttp-jinja2@1.1.0",
          "aiohttp@3.5.3"
        ],
        "upgradePath": [],
        "isUpgradable": false,
        "isPatchable": false,
        "isPinnable": true,
        "name": "aiohttp",
        "version": "3.5.3"
      },
      {
        "CVSSv3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L/E:P",
        "alternativeIds": [],
        "creationTime": "2020-09-25T17:30:26.286074Z",
        "credit": [
          "Yeting Li"
        ],
        "cvssScore": 5.3,
        "description": "## Overview\n[jinja2](https://pypi.org/project/Jinja2/) is a template engine written in pure Python. It provides a Django inspired non-XML syntax but supports inline expressions and an optional sandboxed environment.\n\nAffected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS). The ReDoS vulnerability is mainly due to the `_punctuation_re regex` operator and its use of multiple wildcards. The last wildcard is the most exploitable as it searches for trailing punctuation.\r\n\r\nThis issue can be mitigated by using Markdown to format user content instead of the urlize filter, or by implementing request timeouts or limiting process memory.\r\n\r\n### PoC by Yeting Li\r\n```\r\nfrom jinja2.utils import urlize\r\nfrom time import perf_counter\r\n\r\nfor i in range(3):\r\n    text = \"abc@\" + \".\" * (i+1)*5000 + \"!\"\r\n    LEN = len(text)\r\n    BEGIN = perf_counter()\r\n    urlize(text)\r\n    DURATION = perf_counter() - BEGIN\r\n    print(f\"{LEN}: took {DURATION} seconds!\")\r\n```\n\n## Details\n\nDenial of Service (DoS) describes a family of attacks, all aimed at making a system inaccessible to its original and legitimate users. There are many types of DoS attacks, ranging from trying to clog the network pipes to the system by generating a large volume of traffic from many machines (a Distributed Denial of Service - DDoS - attack) to sending crafted requests that cause a system to crash or take a disproportional amount of time to process.\n\nThe Regular expression Denial of Service (ReDoS) is a type of Denial of Service attack. Regular expressions are incredibly powerful, but they aren't very intuitive and can ultimately end up making it easy for attackers to take your site down.\n\nLet’s take the following regular expression as an example:\n```js\nregex = /A(B|C+)+D/\n```\n\nThis regular expression accomplishes the following:\n- `A` The string must start with the letter 'A'\n- `(B|C+)+` The string must then follow the letter A with either the letter 'B' or some number of occurrences of the letter 'C' (the `+` matches one or more times). The `+` at the end of this section states that we can look for one or more matches of this section.\n- `D` Finally, we ensure this section of the string ends with a 'D'\n\nThe expression would match inputs such as `ABBD`, `ABCCCCD`, `ABCBCCCD` and `ACCCCCD`\n\nIt most cases, it doesn't take very long for a regex engine to find a match:\n\n```bash\n$ time node -e '/A(B|C+)+D/.test(\"ACCCCCCCCCCCCCCCCCCCCCCCCCCCCD\")'\n0.04s user 0.01s system 95% cpu 0.052 total\n\n$ time node -e '/A(B|C+)+D/.test(\"ACCCCCCCCCCCCCCCCCCCCCCCCCCCCX\")'\n1.79s user 0.02s system 99% cpu 1.812 total\n```\n\nThe entire process of testing it against a 30 characters long string takes around ~52ms. But when given an invalid string, it takes nearly two seconds to complete the test, over ten times as long as it took to test a valid string. The dramatic difference is due to the way regular expressions get evaluated.\n\nMost Regex engines will work very similarly (with minor differences). The engine will match the first possible way to accept the current character and proceed to the next one. If it then fails to match the next one, it will backtrack and see if there was another way to digest the previous character. If it goes too far down the rabbit hole only to find out the string doesn’t match in the end, and if many characters have multiple valid regex paths, the number of backtracking steps can become very large, resulting in what is known as _catastrophic backtracking_.\n\nLet's look at how our expression runs into this problem, using a shorter string: \"ACCCX\". While it seems fairly straightforward, there are still four different ways that the engine could match those three C's:\n1. CCC\n2. CC+C\n3. C+CC\n4. C+C+C.\n\nThe engine has to try each of those combinations to see if any of them potentially match against the expression. When you combine that with the other steps the engine must take, we can use [RegEx 101 debugger](https://regex101.com/debugger) to see the engine has to take a total of 38 steps before it can determine the string doesn't match.\n\nFrom there, the number of steps the engine must use to validate a string just continues to grow.\n\n| String | Number of C's | Number of steps |\n| -------|-------------:| -----:|\n| ACCCX | 3 | 38\n| ACCCCX | 4 | 71\n| ACCCCCX | 5 | 136\n| ACCCCCCCCCCCCCCX | 14 | 65,553\n\n\nBy the time the string includes 14 C's, the engine has to take over 65,000 steps just to see if the string is valid. These extreme situations can cause them to work very slowly (exponentially related to input size, as shown above), allowing an attacker to exploit this and can cause the service to excessively consume CPU, resulting in a Denial of Service.\n\n## Remediation\nUpgrade `jinja2` to version 2.11.3 or higher.\n## References\n- [GitHub Additional Information](https://github.com/pallets/jinja/blob/ab81fd9c277900c85da0c322a2ff9d68a235b2e6/src/jinja2/utils.py#L20)\n- [GitHub PR](https://github.com/pallets/jinja/pull/1343)\n",
        "disclosureTime": "2020-09-25T17:29:19Z",
        "exploit": "Proof of Concept",
        "fixedIn": [
          "2.11.3"
        ],
        "functions": [],
        "functions_new": [],
        "id": "SNYK-PYTHON-JINJA2-1012994",
        "identifiers": {
          "CVE": [
            "CVE-2020-28493"
          ],
          "CWE": [
            "CWE-400"
          ],
          "GHSA": [
            "GHSA-g3rq-g295-4j3m"
          ]
        },
        "language": "python",
        "modificationTime": "2021-02-01T19:52:16.877030Z",
        "moduleName": "jinja2",
        "packageManager": "pip",
        "packageName": "jinja2",
        "patches": [],
        "proprietary": true,
        "publicationTime": "2021-02-01T19:52:17Z",
        "references": [
          {
            "title": "GitHub Additional Information",
            "url": "https://github.com/pallets/jinja/blob/ab81fd9c277900c85da0c322a2ff9d68a235b2e6/src/jinja2/utils.py%23L20"
          },
          {
            "title": "GitHub PR",
            "url": "https://github.com/pallets/jinja/pull/1343"
          }
        ],
        "semver": {
          "vulnerable": [
            "[,2.11.3)"
          ]
        },
        "severity": "medium",
        "severityWithCritical": "medium",
        "socialTrendAlert": false,
        "title": "Regular Expression Denial of Service (ReDoS)",
        "from": [
          "test-manifests@0.0.0",
          "aiohttp-jinja2@1.1.0",
          "jinja2@2.10"
        ],
        "upgradePath": [],
        "isUpgradable": false,
        "isPatchable": false,
        "isPinnable": true,
        "name": "jinja2",
        "version": "2.10"
      },
      {
        "CVSSv3": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:C/C:L/I:L/A:L/RL:O",
        "alternativeIds": [],
        "creationTime": "2019-04-07T10:24:16.310959Z",
        "credit": [
          "Unknown"
        ],
        "cvssScore": 6,
        "description": "## Overview\n[jinja2](https://pypi.org/project/Jinja2/) is a template engine written in pure Python. It provides a Django inspired non-XML syntax but supports inline expressions and an optional sandboxed environment.\n\nAffected versions of this package are vulnerable to Sandbox Escape via the `str.format_map`.\n## Remediation\nUpgrade `jinja2` to version 2.10.1 or higher.\n## References\n- [Release Notes](https://palletsprojects.com/blog/jinja-2-10-1-released)\n",
        "disclosureTime": "2019-04-07T00:42:43Z",
        "exploit": "Not Defined",
        "fixedIn": [
          "2.10.1"
        ],
        "functions": [],
        "functions_new": [],
        "id": "SNYK-PYTHON-JINJA2-174126",
        "identifiers": {
          "CVE": [
            "CVE-2019-10906"
          ],
          "CWE": [
            "CWE-265"
          ]
        },
        "language": "python",
        "modificationTime": "2020-06-12T14:36:55.661596Z",
        "moduleName": "jinja2",
        "packageManager": "pip",
        "packageName": "jinja2",
        "patches": [],
        "proprietary": false,
        "publicationTime": "2019-04-07T00:42:43Z",
        "references": [
          {
            "title": "Release Notes",
            "url": "https://palletsprojects.com/blog/jinja-2-10-1-released"
          }
        ],
        "semver": {
          "vulnerable": [
            "[,2.10.1)"
          ]
        },
        "severity": "medium",
        "severityWithCritical": "medium",
        "socialTrendAlert": false,
        "title": "Sandbox Escape",
        "from": [
          "test-manifests@0.0.0",
          "aiohttp-jinja2@1.1.0",
          "jinja2@2.10"
        ],
        "upgradePath": [],
        "isUpgradable": false,
        "isPatchable": false,
        "isPinnable": true,
        "name": "jinja2",
        "version": "2.10"
      },
      {
        "CVSSv3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "alternativeIds": [],
        "creationTime": "2018-06-27T12:31:22.907000Z",
        "credit": [
          "Unknown"
        ],
        "cvssScore": 9.8,
        "description": "## Overview\n[pyyaml](https://pypi.org/project/PyYAML/) is a YAML parser and emitter for Python.\n\nAffected versions of this package are vulnerable to Arbitrary Code Execution due to using the insecure `yaml.load()` function.\n## Remediation\nUpgrade `pyyaml` to version 4.2b1 or higher.\n## References\n- [GitHub Commit](https://github.com/yaml/pyyaml/commit/bbcf95fa051fdba9bbf879332e2f7999b195cf95)\n- [GitHub PR](https://github.com/yaml/pyyaml/pull/74)\n",
        "disclosureTime": "2017-08-26T12:31:22Z",
        "exploit": "Not Defined",
        "fixedIn": [
          "4.2b1"
        ],
        "functions": [],
        "functions_new": [],
        "id": "SNYK-PYTHON-PYYAML-42159",
        "identifiers": {
          "CVE": [
            "CVE-2017-18342"
          ],
          "CWE": [
            "CWE-94"
          ],
          "GHSA": [
            "GHSA-rprw-h62v-c2w7"
          ]
        },
        "language": "python",
        "modificationTime": "2020-06-12T14:37:04.903304Z",
        "moduleName": "pyyaml",
        "packageManager": "pip",
        "packageName": "pyyaml",
        "patches": [],
        "proprietary": false,
        "publicationTime": "2018-06-28T14:59:11Z",
        "references": [
          {
            "title": "GitHub Commit",
            "url": "https://github.com/yaml/pyyaml/commit/bbcf95fa051fdba9bbf879332e2f7999b195cf95"
          },
          {
            "title": "GitHub PR",
            "url": "https://github.com/yaml/pyyaml/pull/74"
          }
        ],
        "semver": {
          "vulnerable": [
            "[,4.2b1)"
          ]
        },
        "severity": "critical",
        "severityWithCritical": "critical",
        "socialTrendAlert": false,
        "title": "Arbitrary Code Execution",
        "from": [
          "test-manifests@0.0.0",
          "pyyaml@3.13"
        ],
        "upgradePath": [],
        "isUpgradable": false,
        "isPatchable": false,
        "isPinnable": true,
        "name": "pyyaml",
        "version": "3.13"
      },
      {
        "CVSSv3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "alternativeIds": [],
        "creationTime": "2020-03-02T13:40:20.621517Z",
        "credit": [
          "Riccardo Schirone (Red Hat)"
        ],
        "cvssScore": 9.8,
        "description": "## Overview\n[pyyaml](https://pypi.org/project/PyYAML/) is a YAML parser and emitter for Python.\n\nAffected versions of this package are vulnerable to Arbitrary Code Execution. It is susceptible to arbitrary code execution when it processes untrusted YAML files through the `full_load` method or with the `FullLoader` loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.\n## Remediation\nUpgrade `pyyaml` to version 5.3.1 or higher.\n## References\n- [GitHub Commit](https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0)\n- [GitHub PR](https://github.com/yaml/pyyaml/pull/386)\n- [Redhat Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1807367)\n",
        "disclosureTime": "2020-03-02T00:00:00Z",
        "exploit": "Not Defined",
        "fixedIn": [
          "5.3.1"
        ],
        "functions": [],
        "functions_new": [],
        "id": "SNYK-PYTHON-PYYAML-559098",
        "identifiers": {
          "CVE": [
            "CVE-2020-1747"
          ],
          "CWE": [
            "CWE-20"
          ],
          "GHSA": [
            "GHSA-6757-jp84-gxfx"
          ]
        },
        "language": "python",
        "modificationTime": "2020-06-12T14:36:55.955917Z",
        "moduleName": "pyyaml",
        "packageManager": "pip",
        "packageName": "pyyaml",
        "patches": [],
        "proprietary": false,
        "publicationTime": "2020-03-02T14:05:05Z",
        "references": [
          {
            "title": "GitHub Commit",
            "url": "https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0"
          },
          {
            "title": "GitHub PR",
            "url": "https://github.com/yaml/pyyaml/pull/386"
          },
          {
            "title": "Redhat Bugzilla",
            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1807367"
          }
        ],
        "semver": {
          "vulnerable": [
            "[0,5.3.1)"
          ]
        },
        "severity": "critical",
        "severityWithCritical": "critical",
        "socialTrendAlert": false,
        "title": "Arbitrary Code Execution",
        "from": [
          "test-manifests@0.0.0",
          "pyyaml@3.13"
        ],
        "upgradePath": [],
        "isUpgradable": false,
        "isPatchable": false,
        "isPinnable": true,
        "name": "pyyaml",
        "version": "3.13"
      },
      {
        "CVSSv3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H/E:F/RL:O/RC:C",
        "alternativeIds": [],
        "creationTime": "2020-07-26T08:29:31.478203Z",
        "credit": [
          "Unknown"
        ],
        "cvssScore": 9.8,
        "description": "## Overview\n[pyyaml](https://pypi.org/project/PyYAML/) is a YAML parser and emitter for Python.\n\nAffected versions of this package are vulnerable to Arbitrary Code Execution. It processes untrusted YAML files through the `full_load` method or with the `FullLoader` loader. This is due to an incomplete fix for CVE-2020-1747\n## Remediation\nUpgrade `pyyaml` to version 5.4 or higher.\n## References\n- [Exploit Writeup](https://hackmd.io/@harrier/uiuctf20)\n- [GitHub Commit](https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc)\n- [GitHub Issue](https://github.com/yaml/pyyaml/issues/420)\n- [RedHat Bugzilla Bug](https://bugzilla.redhat.com/show_bug.cgi?id=1860466)\n- [Research Blog Post](https://blog.arxenix.dev/pyyaml-cve/)\n",
        "disclosureTime": "2020-07-22T00:00:00Z",
        "exploit": "Functional",
        "fixedIn": [
          "5.4"
        ],
        "functions": [],
        "functions_new": [],
        "id": "SNYK-PYTHON-PYYAML-590151",
        "identifiers": {
          "CVE": [
            "CVE-2020-14343"
          ],
          "CWE": [
            "CWE-94"
          ]
        },
        "language": "python",
        "modificationTime": "2021-01-20T14:15:00.359860Z",
        "moduleName": "pyyaml",
        "packageManager": "pip",
        "packageName": "pyyaml",
        "patches": [],
        "proprietary": false,
        "publicationTime": "2020-07-26T13:45:01Z",
        "references": [
          {
            "title": "Exploit Writeup",
            "url": "https://hackmd.io/@harrier/uiuctf20"
          },
          {
            "title": "GitHub Commit",
            "url": "https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc"
          },
          {
            "title": "GitHub Issue",
            "url": "https://github.com/yaml/pyyaml/issues/420"
          },
          {
            "title": "RedHat Bugzilla Bug",
            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1860466"
          },
          {
            "title": "Research Blog Post",
            "url": "https://blog.arxenix.dev/pyyaml-cve/"
          }
        ],
        "semver": {
          "vulnerable": [
            "[0,5.4)"
          ]
        },
        "severity": "critical",
        "severityWithCritical": "critical",
        "socialTrendAlert": false,
        "title": "Arbitrary Code Execution",
        "from": [
          "test-manifests@0.0.0",
          "pyyaml@3.13"
        ],
        "upgradePath": [],
        "isUpgradable": false,
        "isPatchable": false,
        "isPinnable": true,
        "name": "pyyaml",
        "version": "3.13"
      }
    ],
    "upgrade": {},
    "patch": {},
    "ignore": {},
    "pin": {
      "aiohttp@3.5.3": {
        "upgradeTo": "aiohttp@3.7.4",
        "vulns": [
          "SNYK-PYTHON-AIOHTTP-1079232"
        ],
        "isTransitive": true
      },
      "jinja2@2.10": {
        "upgradeTo": "jinja2@2.11.3",
        "vulns": [
          "SNYK-PYTHON-JINJA2-1012994",
          "SNYK-PYTHON-JINJA2-174126"
        ],
        "isTransitive": true
      },
      "pyyaml@3.13": {
        "upgradeTo": "pyyaml@4.2b1",
        "vulns": [
          "SNYK-PYTHON-PYYAML-42159",
          "SNYK-PYTHON-PYYAML-559098",
          "SNYK-PYTHON-PYYAML-590151"
        ],
        "isTransitive": false
      }
    }
  },
  "filesystemPolicy": false,
  "filtered": {
    "ignore": [],
    "patch": []
  },
  "uniqueCount": 6,
  "projectName": "test-manifests",
  "displayTargetFile": "requirements.txt",
  "path": "/home/divyanshuagrawal/Documents/github-actions/crda-action/test-manifests"
}
